const PDFDocument = require('pdfkit');

const COLORS = {
  primary: '#00c8ff',
  accent: '#0f172a',
  text: '#0f172a',
  muted: '#475569',
  high: '#ef4444',
  medium: '#f97316',
  low: '#eab308',
};

const getSeverityColor = (severity) => {
  if (severity === 'High') return COLORS.high;
  if (severity === 'Medium') return COLORS.medium;
  return COLORS.low;
};

const getGrade = (score) => {
  if (score >= 90) return 'A+';
  if (score >= 80) return 'A';
  if (score >= 70) return 'B';
  if (score >= 60) return 'C';
  if (score >= 50) return 'D';
  return 'F';
};

const ensureSpace = (doc, requiredHeight = 120) => {
  if (doc.y + requiredHeight > doc.page.height - 70) {
    doc.addPage();
  }
};

const drawFooter = (doc) => {
  doc
    .font('Helvetica')
    .fontSize(9)
    .fillColor(COLORS.muted)
    .text('Generated by DevSecure', 0, doc.page.height - 35, {
      align: 'center',
    });
};

const drawSectionTitle = (doc, title) => {
  ensureSpace(doc, 40);
  doc.moveDown(0.5);
  doc.font('Helvetica-Bold').fontSize(13).fillColor(COLORS.accent).text(title);
  doc
    .moveTo(50, doc.y + 2)
    .lineTo(doc.page.width - 50, doc.y + 2)
    .lineWidth(1)
    .strokeColor('#cbd5e1')
    .stroke();
  doc.moveDown();
};

const streamPdfReport = (scanData, res) => {
  const filename = `devsecure-report-${Date.now()}.pdf`;

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);

  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  doc.pipe(res);

  // Header banner.
  doc.rect(0, 0, doc.page.width, 85).fill(COLORS.accent);
  doc.font('Helvetica-Bold').fontSize(24).fillColor(COLORS.primary).text('DevSecure', 50, 22);
  doc.font('Helvetica').fontSize(12).fillColor('#e2e8f0').text('AI Powered Web Security Scanner', 50, 54);

  doc.y = 105;

  const score = scanData.securityScore || 0;
  const grade = scanData.securityGrade || getGrade(score);

  doc.font('Helvetica-Bold').fontSize(18).fillColor(COLORS.accent).text('DevSecure Security Report');

  doc.moveDown(0.8);
  doc.font('Helvetica').fontSize(11).fillColor(COLORS.text).text(`Target URL: ${scanData.url || 'N/A'}`);
  doc.text(`Scan Date: ${scanData.scannedAt ? new Date(scanData.scannedAt).toLocaleString() : 'N/A'}`);
  doc.text(`Security Score: ${score}`);
  doc.text(`Security Grade: ${grade}`);

  drawSectionTitle(doc, 'Detected Vulnerabilities');

  const issues = Array.isArray(scanData.issues) ? scanData.issues : [];
  if (!issues.length) {
    doc
      .font('Helvetica')
      .fontSize(11)
      .fillColor(COLORS.muted)
      .text('No vulnerabilities detected in the current scan output.');
  } else {
    issues.forEach((issue, index) => {
      ensureSpace(doc, 120);

      doc
        .roundedRect(50, doc.y, doc.page.width - 100, 105)
        .lineWidth(1)
        .strokeColor('#cbd5e1')
        .stroke();

      const startY = doc.y + 8;
      const severity = issue.severity || 'Low';
      const issueTitle = issue.title || issue.name || `Issue ${index + 1}`;
      const owasp = issue.owaspCategory || issue.owasp || 'A05 Security Misconfiguration';
      const explanation = issue.explanation || 'Explanation not available.';
      const impact = issue.impact || 'Impact details not available.';
      const fix = issue.suggestedFix || issue.suggested_fix || 'Suggested fix not available.';

      doc
        .font('Helvetica-Bold')
        .fontSize(10)
        .fillColor(COLORS.accent)
        .text(`Name: ${issueTitle}`, 58, startY, { width: doc.page.width - 118 });

      doc
        .font('Helvetica-Bold')
        .fontSize(10)
        .fillColor(getSeverityColor(severity))
        .text(`Severity: ${severity}`, 58, startY + 16);

      doc
        .font('Helvetica')
        .fontSize(10)
        .fillColor(COLORS.text)
        .text(`OWASP Category: ${owasp}`, 200, startY + 16);

      doc.font('Helvetica').fontSize(9).fillColor(COLORS.text);
      doc.text(`Explanation: ${explanation}`, 58, startY + 34, { width: doc.page.width - 118 });
      doc.text(`Impact: ${impact}`, 58, startY + 52, { width: doc.page.width - 118 });
      doc.text(`Suggested Fix: ${fix}`, 58, startY + 70, { width: doc.page.width - 118 });

      doc.y += 114;
    });
  }

  drawSectionTitle(doc, 'AI Security Summary');
  const summaryPoints = Array.isArray(scanData.aiSummaryPoints) ? scanData.aiSummaryPoints : [];

  if (!summaryPoints.length) {
    doc.font('Helvetica').fontSize(11).fillColor(COLORS.muted).text('No AI summary captured for this report.');
  } else {
    summaryPoints.forEach((point) => {
      ensureSpace(doc, 30);
      doc.font('Helvetica').fontSize(11).fillColor(COLORS.text).text(`- ${point}`, { indent: 8 });
      doc.moveDown(0.2);
    });
  }

  drawSectionTitle(doc, 'AI Recommendations');
  const aiRecommendations = Array.isArray(scanData.aiRecommendations)
    ? scanData.aiRecommendations
    : Array.isArray(scanData.recommendations)
    ? scanData.recommendations
    : [];

  if (!aiRecommendations.length) {
    doc
      .font('Helvetica')
      .fontSize(11)
      .fillColor(COLORS.muted)
      .text('No AI recommendations captured for this report.');
  } else {
    aiRecommendations.forEach((recommendation) => {
      ensureSpace(doc, 30);
      doc.font('Helvetica').fontSize(11).fillColor(COLORS.text).text(`- ${recommendation}`, { indent: 8 });
      doc.moveDown(0.2);
    });
  }

  drawFooter(doc);
  doc.end();
};

module.exports = {
  streamPdfReport,
};
